apiVersion: v1
kind: Route
metadata:
  name: "appium"
  labels:
    metrics: "appium"
    app: "cicd-appium"
    version: "1.6.3"
spec:
  host: ''
  port:
    targetPort: 4723-http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: "appium"
    weight: 100