apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appium
  labels:
    metrics: "appium"
    app: cicd-appium
    version: "1.6.3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi