apiVersion: v1
kind: DeploymentConfig
metadata:
  name: "emulator"
  labels:
    metrics: "appium"
spec:
  replicas: 1
  selector:
    metrics: "emulator"
  template:
    metadata:
      labels:
        metrics: "emulator"
    spec:
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: 500m
          memory: 512Mi
      containers:
      - name: emulator
        image: "172.30.1.1:5000/appium/emulator:1"
        ports:
        - containerPort: 5902
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 120
          tcpSocket:
            port: 5902
          timeoutSeconds: 5
        readinessProbe:
          initialDelaySeconds: 180
          tcpSocket:
            port: 5902
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: "/android_sdk/*"
          name: "emulator"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: "emulator"
        persistentVolumeClaim:
          claimName: "emulator"
    test: false