apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulator
  labels:
    metrics: "emulator"
    app: cicd-genymotion
    version: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi