apiVersion: v1
kind: Route
metadata:
  name: "emulator"
  labels:
    metrics: "emulator"
    app: "cicd-emulator"
    version: "1"
spec:
  host: ''
  port:
    targetPort: 4723-http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: "emulator"
    weight: 100