apiVersion: v1
kind: Service
metadata:
  name: emulator
  labels:
    metrics: "emulator"
    app: "cicd-emulator"
spec:
  ports:
  - name: 4723-http
    port: 4723
    nodePort: 30036
    protocol: TCP
    targetPort: 4723
  selector:
    metrics: emulator
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}